runtime: php73
api_version: 1
threadsafe: true

handlers:
- url: /
  script: index.html 

- url: /app.js
  script: app.js 

- url: /css/app.css
  script: /css/app.css

- url: /(.*\.(png|jpg|ico))$
  static_files: static/\1

- url: /(.*\.(ttf|woff))$
  static_files: static/\1

- url: /ws/ws.php
  script: /ws/ws.php

- url: /.*
  script: not_found.app
