<!-- matches are created with ladder and team having been created.
     a numer of matches need to be played by each team to have a winner

-->

<?php
  error_reporting(0); // Ignoring the error generated by session start
  session_start();
  if(!isset($_SESSION['UserPrivileges']) && $_SESSION['UserPrivileges'] != 1){ // Checks to see if the userprivileges session is set and to see if its admin or not
    header('location: ../');
  }
?>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LANLAdder HOME</title>
    <script src="../js/code.js"></script>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">

    <link rel="stylesheet" href="../css/style.css" type="text/css">
    <script type = "text/javascript" src = "https://code.jquery.com/jquery-2.1.1.min.js"></script>           
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script> 
</head>
<?php
    require_once('../functions.php');
    print '<body>';
    ?>
    <nav class="navbar_admin">
      <div class="nav-wrapper">
        <ul class="left">
          <li class="waves-effect waves-light"><a href="../index.php">Home</a></li>
          <li class="waves-effect waves-light"><a href="createladder.php">Create Ladder</a></li>
          <li class="waves-effect waves-light"><a href="creatematch.php">Create Match</a></li>
        </ul>
        <ul class="right">
          <li class="waves-effect waves-light"><a href="../control/logout.php">Logout</a></li>
        </ul>
      </div>
    </nav>
    <form class="" action="admincontroller.php" method="post">
      <h1>Create A Match</h1>
      <div class="container">
        <fieldset>
          <div class="field-container">
            <label for="game"><b>Game</b></label>
            <div class="input-field col s12">
                <select name="game" class="blue-grey darken-4">
                <option value="" disabled selected>Choose a game</option>
                  <?php 
                    $results = ladder_list();
                    foreach ($results as $team) {
                      echo '<option value="' . $team['id'] . '" Name="team"> ' . $team['game'] . '</option>';
                    } 
                  ?>
                </select>
            </div>
            <div class="field-container">
              <label for="team_a"><b>Team A</b></label>
              <select class="blue-grey darken-4" name="team_a">
              <option value="" disabled selected>Choose team a</option>
                  <?php 
                    $results = team_list();
                    foreach ($results as $team) {
                      if(!preg_match('/^Unset$/i', $team['team_name'])){ // Tests to see if the game is not Unset
                        echo '<option value="' . $team['id'] . '" Name="team"> ' . $team['team_name'] . '</option>';
                      }
                    } 
                  ?>
              </select>
            </div>
            <label for="team_b"><b>Team B</b></label>
            <select class="blue-grey darken-4" name="team_b">
              <option value="" disabled selected>Choose team b</option>
                  <?php 
                    $results = team_list();
                    foreach ($results as $team) {
                      if(!preg_match('/^Unset$/i', $team['team_name'])){ // Tests to see if the game is not Unset
                        echo '<option value="' . $team['id'] . '" Name="team"> ' . $team['team_name'] . '</option>';
                      }
                    } 
                  ?>
              </select>
            <div class="">
              <button class="btn align-right" type="submit" value="match">Publish Match</button>
            </div>
          </div>
        </fieldset>
      </div>
    </form>
    <?php
    print '</body>';
?>
